### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nsleche** [thii/Notie#11]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by thii** [comment]
I personally don't use this anymore. Do you want to take over this project?

**Comment by ballerabdude** [comment]
@nschucky I am painfully updating my project to swift 3. Since I'm using this library I can put in a pull request when I update it to swift 3.

**Comment by thii** [comment]
Sorry for the delayed response. It has been updated to Swift 3 now.
