### ISSUE TITLE
Change name of cocoapods repo

### ISSUE THREAD

**Issue by jaredreich** [thii/Notie#4]
Very cool of you to make an iOS version of https://github.com/jaredreich/notie.js... but I'm already working on the official iOS version of notie.js, so could you please change the name of the cocoapods repo (https://cocoapods.org/?q=notie) so that I can use the official name that I originally came up with? It would be very much appreciated...

**Comment by thii** [comment]
I just googled a bit but unfortunately there seems to be no way to change the name of a podspec. However, you can use the same name if you point to your own podspec.

**Comment by thii** [comment]
I'm closing this now. Feel free to reopen it if you have any idea.
