### ISSUE TITLE
how can I get the text from input?

### ISSUE THREAD

**Issue by 128keaton** [thii/Notie#6]
hello, I am wondering how I can fetch the input text from a notie view. Thanks!

**Comment by thii** [comment]
Haven't implemented it though

**Comment by 128keaton** [comment]
@thii oh. uh. will it become a feature?

**Comment by thii** [comment]
@128keaton Not sure though. You can take over this and improve it if you want.

**Comment by 128keaton** [comment]
@thii thanks :)
